# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Videotracker Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        ./src/install.deps.sh
        source venv/bin/activate
        ./src/install_deps.sh
        pip install coverage
        pip install pyvirtualdisplay
    - name: Tests
      run: |
        python3 -m unittest discover -s tests -p "test_*.py"
    - name: Coverage
      run: |
        python3 -m coverage run -m unittest discover -s tests -p "test_*.py"
        python3 -m coverage report -m -i
